#!/bin/bash

path="/production-dupont-ftp/FTP_dealers"
cat ./list-user.txt | while read line
do
echo $line > ./tmp.txt
i=$(cat ./tmp.txt | awk  '{print $1}')
echo $i
useradd -g ftp -m $i -p $i
mkdir $path/$i
chown -R $i:root $path/$i
usermod -d $path/$i $i
rm -rf /home/$i
ln -s $path/$i/ /home/$i
echo $i | sudo tee -a /etc/vsftpd.userlist
sudo systemctl reload vsftpd
done
